server:
  port: 8206
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.94.107.24:3306/gmall_product
  redis:
    host: 47.94.107.24
    password:
    database: 0
    port: 6379
  zipkin:
    base-url: http://47.94.107.24:9411
  rabbitmq:
    host: 47.94.107.24
    port: 5672
    username: guest
    password: guest